# Generated by Django 2.0.7 on 2018-07-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180714_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchparticipant',
            name='motivation',
            field=models.TextField(default='i love to be a part of your question'),
        ),
    ]
